if math.random(5) == 1
    then
        error("Random failure")
    end
    return "Random success"
